[parity]
chain = "./spec/spec.json"
base_path = "./nodes/validator/"

[network]
port = 40301
discovery = true
reserved_peers = "./nodes/reserved_peers"

[rpc]
disable = true

[account]
unlock = ["0xce2f23a9fb7f9a9ee265867ec502c0f39ddf9293"]
password = ["./nodes/validator/node.pwd"]

[mining]
force_sealing = true
engine_signer = "0xce2f23a9fb7f9a9ee265867ec502c0f39ddf9293"
reseal_on_txs = "none"

[websockets]
disable = true

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"

